name: Build Mar-rat-hon for Linux
# Registered for Mar-rat-hon Actions

on: [workflow_dispatch, workflow_call]

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
        
    - name: Configure
      uses: ./.github/actions/configure-linux
        
    - run: make dist
          
    - run: make datadist
        
    - name: Build flatpaks
      run: | 
        sudo apt-get install flatpak-builder
        sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        sudo flatpak install flathub org.gnome.Platform//49 org.gnome.Sdk//49 -y
        flatpak-builder --repo=flatpak/repo --force-clean \
          flatpak/Mar-rat-hon.build \
          flatpak/io.github.visageeee.MarRatHon.yml
        flatpak build-bundle flatpak/repo \
          Mar-rat-hon-x86_64.flatpak \
          io.github.visageeee.MarRatHon
        
    - name: Upload
      uses: actions/upload-artifact@v6
      with:
        name: mar-rat-hon-linux-release
        if-no-files-found: error
        path: |
         *.tar.bz2
         *.zip
         *.flatpak
